export {default as Header} from './Header/Header.js';
export {default as Bellows} from './Bellows/Bellows.js';
export {default as Footer} from './Footer/Footer.js';
export {default as Carousel} from './Carousel';
export {default as Footer2} from './Footer2';
export {default as Connect} from './Connect';
export {default as Communication} from './SecondPage/Communication/Communication.jsx';
export {default as Research} from './SecondPage/Research/Research.js';
export {default as Solution} from './SecondPage/Solution/Solution.js';